version: '3.8'
services:
  frontend:
    build:
      context: .
      target: dev_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/:/app
    depends_on:
      - backend
      - mysql

  backend:
    build:
      context: .
      target: dev_backend
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysql:3306/gesemp
    volumes:
      - ./backend/:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=gesemp
      - MYSQL_PASSWORD=gesemp
      - MYSQL_DATABASE=gesemp
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

volumes:
  mysql_data:
  mysql_config:
