version: '3.8'
services:
  frontend:
    image: wilfrieddang07/gesemp_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/:/app
    depends_on:
      - backend
      - mysql

  backend:
    image: wilfrieddang07/gesemp_backend
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysql:3307/gesemp  # Utilisez le port 3307
    volumes:
      - ./backend/:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"  # Assurez-vous que le port externe est 3307
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=gesemp
      - MYSQL_PASSWORD=gesemp
      - MYSQL_DATABASE=gesemp
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

volumes:
  mysql_data:
  mysql_config:
